### ISSUE TITLE
build-deploy check immediately fails after using this repo as template

### ISSUE THREAD

**Issue by durandg12** [computorg/template-computo-R#6]
The error seems to be that tlmgr needs to be updated
<img width="861" alt="Capture d’écran 2024-06-26 à 15 31 45" src="https://github.com/computorg/template-computo-R/assets/45902885/ab2c8198-4c58-4310-bf20-6129a86424fa">

**Comment by jchiquet** [comment]
thanks for the follow-up. I patched an (hopefully) temporary fix for tlmgr.
