### ISSUE TITLE
build action still fails

### ISSUE THREAD

**Issue by durandg12** [computorg/template-computo-R#7]
I used the updated code just pushed to solve #6 

Now the build still fails, but later in the process.

<img width="936" alt="Capture d’écran 2024-06-26 à 17 45 28" src="https://github.com/computorg/template-computo-R/assets/45902885/6178a6a9-9c3f-4d8a-9284-cd843d4793a3">

**Comment by jchiquet** [comment]
This error occurs tpically, when you have two or more qmd files in your
repo when quarto is expecting only a single one.

**Comment by durandg12** [comment]
Thanks build is now passing
